tap "homebrew/cask"
tap "caskroom/fonts"

cask_args appdir: "/Applications"

cask "font-source-code-pro"
cask "alacritty"

brew "coreutils"
brew "diffutils"
brew "findutils"
brew "ed"
brew "gawk"
brew "gnu-sed"
brew "gnu-which"
brew "grep"
brew "less"
brew "m4"
brew "make"

brew "gzip"
brew "gnu-tar"
brew "unzip"

brew "bash"
brew "tmux"

brew "nano"
brew "vim"

brew "git"
cask "wireshark"
cask "balenaetcher"

brew "jq"
brew "bat"
brew "exa"
brew "ripgrep"
brew "fd"
brew "htop"

cask "docker"
brew "go"
brew "node"

cask "aptible"
brew "gpg2"
brew "chruby"
brew "ruby-install"

cask "little-snitch"
cask "slack"
cask "zoomus"
cask "encryptme"

# mas can only reinstall once added to account
mas "1Password", id: 1333542190
# mas "ScreenshotMenu", id: 562169322
