tap "homebrew/cask"
tap "caskroom/fonts"
tap "hashicorp/tap"

cask_args appdir: "/Applications"

cask "font-source-code-pro"
cask "alacritty"
cask "amethyst"
cask "pock"

brew "coreutils"
brew "diffutils"
brew "findutils"
brew "ed"
brew "gawk"
brew "gnu-sed"
brew "gnu-which"
brew "grep"
brew "less"
brew "m4"
brew "make"
brew "pstree"

brew "gzip"
brew "gnu-tar"
brew "unzip"

brew "bash"
brew "tmux"

brew "nano"
brew "vim"
brew "lnav"

brew "git"
brew "git-delta"
brew "gh"
brew "gpg2"

cask "balenaetcher"
cask "kap"
cask "lepton"

brew "jq"
brew "bat"
brew "exa"
brew "ripgrep"
brew "fd"
brew "htop"
brew "procs"

brew "bats"
brew "shellcheck"
brew "shfmt"
brew "hadolint"

cask "docker"
cask "multipass"
brew "go"
brew "node"

brew "postgresql"
brew "postgresql@9.6"

cask "aptible"
brew "awscli"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/packer"
brew "travis"

brew "chruby"
brew "ruby-install"
brew "nvm"
brew "pipx"

cask "little-snitch"
cask "slack"
cask "zoomus"
cask "encryptme"

# mas can only reinstall once added to account
mas "1Password", id: 1333542190
mas "Hidden Bar", id: 1452453066
mas "Microsoft Remote Desktop", id: 1295203466
