#!/usr/bin/env bash

## called like add_git_ssh_key github rsa

SERVICE=$1
KEY=$2

TOKEN=$( git config --get ${SERVICE}.token )

PUBKEY=$( cat $HOME/.ssh/${SERVICE}_id_$KEY.pub )
TITLE="$(hostname)-$KEY"

if [[ $SERVICE == "github" ]]; then
    http -j POST https://api.github.com/user/keys \
        Authorization:"token $TOKEN" \
        title="$TITLE" \
        key="$PUBKEY"
else
    http -j POST https://gitlab.com/api/v3/user/keys \
        PRIVATE-TOKEN:"$TOKEN" \
        title="$TITLE" \
        key="$PUBKEY"
fi
