#!/usr/bin/env bash

if [[ $OSTYPE == 'linux-gnu' ]]; then
  export OS="linux"

  alias ls='ls -F --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
else
  export OS="osx"

  alias ls="ls -GF"
fi

if [[ $(which bat) ]]; then
  alias l='bat --style="numbers,changes"'
elif [[ $(which less) ]]; then
  alias l="less"
else
  alias l="more"
fi

if [[ $(which exa) ]]; then
  alias ls="exa -F --group-directories-first --color=auto"
  alias lsl="exa -alFgh@ --group-directories-first --git --color=auto"
else
  alias lsl="ls -ahl"
fi

alias rmd="rm -rf"

if [[ $(which code) ]]; then
  alias edit="code"
elif [[ $(which micro) ]]; then
  alias edit="micro"
else
  alias edit="nano"
fi

alias hex="hexdump -Cv"
alias hexstruct="xxd -i"

alias tcpconnections="sudo ss -lntp TCP"

alias master="git checkout master && git pull"

# Get a sum of the total size of a file/folder in human readable units:
alias space="du -sh"

#List file sizes of a directory and any subdirectories in KB:
alias lsspace="du -k"

alias ps="ps aux"

alias jekyll-serve="docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 127.0.0.1:4000:4000 jekyll/jekyll jekyll serve"

alias pacnew='find /etc -regextype posix-extended -regex ".+\.pac(new|save)" 2> /dev/null'

alias tfpr='terraform refresh && terraform plan -refresh=false -no-color | head -n -7 | tail -n +5 | xclip -selection c'

gosrc () {
  if [[ -d "$GOPATH/src/github.com/adhocteam" ]]; then
    cd "$GOPATH/src/github.com/adhocteam"
    return 0
  fi

  cd "$GOPATH/src/github.com/robertfairhead"
}

compress_img () {
  convert $1 -filter Triangle -define filter:support=2 -thumbnail 400 -unsharp 0.25x0.25+8+0.065 -dither None -posterize 136 -quality 82 -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB -strip $1
}

docker-here () {
  docker run -it --rm -v "$(pwd):/src" -w "/src" -u $(id -u):$(id -g) --entrypoint "" $1 bash
}
