# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, only update PATH
case $- in
*i*) ;;
*)
  # shellcheck source=path
  source "$HOME/dotfiles/bash/path"
  return
  ;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL="erasedups:ignoreboth"

# Don't record some commands
export HISTIGNORE="&:[]*:exit:ls:bg:fg:history:clear"

# append to the history file, don't overwrite it
shopt -s histappend

# Save all lines of a multi-line command as one line in history
shopt -s cmdhist

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=5000
HISTFILESIZE=10000

export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$"\n"}history -a; history -c; history -r"

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

if command -v dircolors >/dev/null 2>&1; then
  eval "$(dircolors -b "$HOME/dotfiles/bash/dir_colors")"
fi

# shellcheck source=path
source "$HOME/dotfiles/bash/path"
# shellcheck source=aliases
source "$HOME/dotfiles/bash/aliases"

if command -v starship >/dev/null 2>&1; then
  eval "$(starship init bash)"
else
  # shellcheck source=prompt
  source "$HOME/dotfiles/bash/prompt"
fi

# shellcheck source=env
source "$HOME/dotfiles/bash/env"

# Use system-wide bash completions if available
if [[ -f /usr/local/etc/bash_completion ]]; then
  source /usr/local/etc/bash_completion
fi

# Use my local ones as well
for bashcmp in "$HOME"/dotfiles/completions/*.bash-completion; do
  # shellcheck source=/dev/null
  source "$bashcmp"
done

# If we have local settings, pull those in
if [[ -f "$HOME/.bash_local" ]]; then
  # shellcheck source=/dev/null
  source "$HOME/.bash_local"
fi

if [[ ! -f "$HOME/.alacritty_local.yml" ]]; then
  echo -e "font:\n  size: 10" >.alacritty_local.yml
fi
