format = """
$hostname${custom.system_icons}$kubernetes$directory$git_branch${custom.origin}$git_status$git_state\
$line_break\
$status$character"""

# Don't print a new line at the start of the prompt
add_newline = false

[hostname]
format = "歷($style)"
ssh_only = true
style = "bold"

[directory]
format = "in [$path]($style)[$read_only]($read_only_style) "
style = "blue"
truncation_length = 2
truncation_symbol = "…/"

[kubernetes]
disabled = false
format = '[\[$context|$namespace\]]($style) '
style = "cyan"
[kubernetes.context_aliases]
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

[git_branch]
format = "on [$branch]($style)"
truncation_length = 128
truncation_symbol = "…"
style = "purple"

[git_status]
format = '([$deleted$renamed$modified$staged$untracked$ahead_behind ]($style))'
style = "yellow"
modified = "?"
staged = "!"
untracked = "+"

[character]
success_symbol = "[>](blue)"
error_symbol = "[➜](bold red) "

[custom.origin]
description = "current branch does not have a tracking branch on the origin remote"
command = "[[ -z $(git rev-list --count --right-only @{u}.. 2> /dev/null) ]] && echo -e '∅'"
when = "[[ $(command git rev-parse --is-inside-work-tree 2>/dev/null) == true ]]"
shell = ["bash", "--noprofile", "--norc"]
style = "bold red"
format = "[$output ]($style)"

[custom.system_icons]
description = "Show system icons"
command     = '([ $(uname -s) == "Darwin" ] && echo -e ) || ([ $(uname -s) == "Linux" ] && echo -e )'
format      = "[$output]($style) "
style       = "bold"
shell       = ["bash", "--noprofile", "--norc"]
when        = "true"
